<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gp</string>
	</array>
	<key>name</key>
	<string>GCodePlus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>[^\w@](ABS|ACOS|ASIN|ATAN|COS|LN|EXP|FIX|FUP|MOD|ROUND|SQRT|SIN|TAN)</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>@header</string>
			<key>end</key>
			<string>@endheader</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//.*)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^@(delay)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>entity.name.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^@(if|eval|define|endif|switch|case|endcase|error|delay)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>keyword.control</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^@(endif|endswitch|endcase|header|endheader|defaultcase|endprogram|else)\s.*</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^N@{0,1}</string>
			<key>contentName</key>
			<string>entity.name.function</string>
			<key>end</key>
			<string>\W</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^@program\s+</string>
			<key>contentName</key>
			<string>entity.name.function</string>
			<key>end</key>
			<string>\W</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>GOTO</string>
			<key>contentName</key>
			<string>entity.name.function</string>
			<key>end</key>
			<string>[^\w@]</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@0x\h+|\W\d+)</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\w+[\w\d]*</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\W(GT|LT|GE|LE|EQ|NE|OR|AND|XOR|NOT)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(M98|M99|IF|THEN|WHILE|DO\d+|END\d+)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(M\d+|G\d+)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#\d+\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#\w+\b</string>
			<key>name</key>
			<string>constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#@\w+\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gcodeplus</string>
	<key>uuid</key>
	<string>03CD0311-9CC5-472E-A325-925BAA86591D</string>
</dict>
</plist>
